export const theme = {
  color: {
    bg: "#FDF7EC",
    bgAlt: "#FBF4E6",
    bgSection: "#F5EFDF",
    primary: "#1A605A",
    primaryDark: "#14504B",
    ink: "#2B2B26",
    text: "#54574E",
    textSoft: "#5E6157",
    muted: "#5A6853",
    accent: "#46543F",
    line: "#E4DFCF",
    lineSoft: "#DCD6C4",
    sage: "#BAC5B4",
    sageBorder: "#C5CFBB",
    onPrimary: "#FDF7EC",
    onPrimarySoft: "#EFEEE4",
    onPrimaryMuted: "#DDE8E5",
    onPrimaryLabel: "#C3DAD5",
    inputBg: "#FFFCF4",
    placeholder: "#A8A497",
  },
  font: {
    serif: "'Cormorant Garamond', serif",
    sans: "'Jost', system-ui, sans-serif",
    script: "'Style Script', cursive",
  },
} as const;
